import { SWSELogger } from "/systems/foundryvtt-swse/scripts/utils/logger.js";
import { HooksRegistry } from "/systems/foundryvtt-swse/scripts/infrastructure/hooks/hooks-registry.js";
import { registerCombatHooks } from "/systems/foundryvtt-swse/scripts/infrastructure/hooks/combat-hooks.js";
import { registerActorHooks } from "/systems/foundryvtt-swse/scripts/infrastructure/hooks/actor-hooks.js";
import { registerUIHooks } from "/systems/foundryvtt-swse/scripts/infrastructure/hooks/ui-hooks.js";
import { registerRerollListeners } from "/systems/foundryvtt-swse/scripts/species/species-reroll-handler.js";
import { SWSECombatActionBrowser } from "/systems/foundryvtt-swse/scripts/apps/combat-action-browser.js";
import { isMobileCandidate } from "/systems/foundryvtt-swse/scripts/ui/mobile-mode-detector.js";
import { registerMobilePrompt } from "/systems/foundryvtt-swse/scripts/ui/mobile-mode-prompt.js";
import LightsaberLightSync from "/systems/foundryvtt-swse/scripts/utils/lightsaber-light-sync.js";
import MobileMode from "/systems/foundryvtt-swse/scripts/ui/mobile-mode-manager.js";
import { FeatActionListeners } from "/systems/foundryvtt-swse/scripts/engine/feats/feat-action-listeners.js";
import { registerGrappleFeatActions } from "/systems/foundryvtt-swse/scripts/engine/feats/grapple-feat-actions.js";
import { registerGrappleRuntimePatches } from "/systems/foundryvtt-swse/scripts/engine/feats/grapple-runtime-patches.js";
import { registerGrappleFeatNormalizationHooks } from "/systems/foundryvtt-swse/scripts/engine/feats/grapple-feat-normalization-hooks.js";
import { registerRiflemasterNormalizationHooks } from "/systems/foundryvtt-swse/scripts/engine/feats/riflemaster-normalization-hooks.js";
import { registerRiflemasterRuntimePatches } from "/systems/foundryvtt-swse/scripts/engine/feats/riflemaster-runtime-patches.js";
import { registerPistoleerNormalizationHooks } from "/systems/foundryvtt-swse/scripts/engine/feats/pistoleer-normalization-hooks.js";
import { registerPistoleerRuntimePatches } from "/systems/foundryvtt-swse/scripts/engine/feats/pistoleer-runtime-patches.js";
import { registerSniperNormalizationHooks } from "/systems/foundryvtt-swse/scripts/engine/feats/sniper-normalization-hooks.js";
import { registerSniperRuntimePatches } from "/systems/foundryvtt-swse/scripts/engine/feats/sniper-runtime-patches.js";
import { registerDualWeaponMasteryNormalizationHooks } from "/systems/foundryvtt-swse/scripts/engine/feats/dual-weapon-mastery-normalization-hooks.js";
import { registerDualWieldRuntimePatches } from "/systems/foundryvtt-swse/scripts/engine/feats/dual-wield-runtime-patches.js";
import { registerCoreCombatReactionNormalizationHooks } from "/systems/foundryvtt-swse/scripts/engine/feats/core-combat-reaction-normalization-hooks.js";
import { registerCoreCombatReactionRuntimePatches } from "/systems/foundryvtt-swse/scripts/engine/feats/core-combat-reaction-runtime-patches.js";
import { registerCoreAttackOptionNormalizationHooks } from "/systems/foundryvtt-swse/scripts/engine/feats/core-attack-option-normalization-hooks.js";
import { registerCoreAttackOptionRuntimePatches } from "/systems/foundryvtt-swse/scripts/engine/feats/core-attack-option-runtime-patches.js";
import { registerRageFeatNormalizationHooks } from "/systems/foundryvtt-swse/scripts/engine/feats/rage-feat-normalization-hooks.js";
import { registerAreaExplosivesFeatNormalizationHooks } from "/systems/foundryvtt-swse/scripts/engine/feats/area-explosives-feat-normalization-hooks.js";
import { registerAreaExplosivesRuntimePatches } from "/systems/foundryvtt-swse/scripts/engine/feats/area-explosives-runtime-patches.js";
import { registerMobilityPositioningFeatNormalizationHooks } from "/systems/foundryvtt-swse/scripts/engine/feats/mobility-positioning-feat-normalization-hooks.js";
import { registerMobilityPositioningRuntimePatches } from "/systems/foundryvtt-swse/scripts/engine/feats/mobility-positioning-runtime-patches.js";
import { registerDefenseAvoidanceFeatNormalizationHooks } from "/systems/foundryvtt-swse/scripts/engine/feats/defense-avoidance-feat-normalization-hooks.js";
import { registerDefenseAvoidanceRuntimePatches } from "/systems/foundryvtt-swse/scripts/engine/feats/defense-avoidance-runtime-patches.js";
import { registerActionSpeedRuntimePatches } from "/systems/foundryvtt-swse/scripts/engine/feats/action-speed-runtime-patches.js";
import { registerAttackOptionsFeatNormalizationHooks } from "/systems/foundryvtt-swse/scripts/engine/feats/attack-options-feat-normalization-hooks.js";
import { registerMeleeCloseCombatFeatNormalizationHooks } from "/systems/foundryvtt-swse/scripts/engine/feats/melee-close-combat-feat-normalization-hooks.js";
import { registerRangedCombatFeatNormalizationHooks } from "/systems/foundryvtt-swse/scripts/engine/feats/ranged-combat-feat-normalization-hooks.js";
import { registerDamageThresholdFeatNormalizationHooks } from "/systems/foundryvtt-swse/scripts/engine/feats/damage-threshold-feat-normalization-hooks.js";
import { registerSpeciesOriginFeatNormalizationHooks } from "/systems/foundryvtt-swse/scripts/engine/feats/species-origin-feat-normalization-hooks.js";
import { registerCombatFeatDamageRuntimePatches } from "/systems/foundryvtt-swse/scripts/engine/feats/combat-feat-damage-runtime-patches.js";
import { registerWeaponArmorRiderNormalizationHooks } from "/systems/foundryvtt-swse/scripts/engine/feats/weapon-armor-rider-normalization-hooks.js";
import { registerWeaponArmorRiderRuntimePatches } from "/systems/foundryvtt-swse/scripts/engine/feats/weapon-armor-rider-runtime-patches.js";
import { registerMartialArtsFeatNormalizationHooks } from "/systems/foundryvtt-swse/scripts/engine/feats/martial-arts-feat-normalization-hooks.js";
import { registerUnarmedStyleFeatNormalizationHooks } from "/systems/foundryvtt-swse/scripts/engine/feats/unarmed-style-feat-normalization-hooks.js";
import { registerAbilityMetaSchemaDefaultHooks } from "/systems/foundryvtt-swse/scripts/engine/feats/ability-meta-schema-default-hooks.js";
import { registerWeaponFoundationFeatNormalizationHooks } from "/systems/foundryvtt-swse/scripts/engine/feats/weapon-foundation-feat-normalization-hooks.js";
import { registerUnknownRegionsWeaponFeatNormalizationHooks } from "/systems/foundryvtt-swse/scripts/engine/feats/unknown-regions-weapon-feat-normalization-hooks.js";
import { registerWeaponCriticalFeatNormalizationHooks } from "/systems/foundryvtt-swse/scripts/engine/feats/weapon-critical-feat-normalization-hooks.js";
import { registerWeaponAutofireFeatNormalizationHooks } from "/systems/foundryvtt-swse/scripts/engine/feats/weapon-autofire-feat-normalization-hooks.js";
import { registerWeaponAutofireRiderRuntimePatches } from "/systems/foundryvtt-swse/scripts/engine/feats/weapon-autofire-rider-runtime-patches.js";
import { registerWeaponLeftoverFeatNormalizationHooks } from "/systems/foundryvtt-swse/scripts/engine/feats/weapon-leftover-feat-normalization-hooks.js";
import { registerWeaponMissRiderRuntimePatches } from "/systems/foundryvtt-swse/scripts/engine/feats/weapon-miss-rider-runtime-patches.js";
import { registerSportHunterNormalizationHooks } from "/systems/foundryvtt-swse/scripts/engine/feats/sport-hunter-normalization-hooks.js";
import { registerSportHunterRuntimePatches } from "/systems/foundryvtt-swse/scripts/engine/feats/sport-hunter-runtime-patches.js";
import { registerRemainingWeaponArmorFeatNormalizationHooks } from "/systems/foundryvtt-swse/scripts/engine/feats/remaining-weapon-armor-feat-normalization-hooks.js";
import { registerRelentlessAttackRuntimePatches } from "/systems/foundryvtt-swse/scripts/engine/feats/relentless-attack-runtime-patches.js";
import { registerStarshipVehicleFeatNormalizationHooks } from "/systems/foundryvtt-swse/scripts/engine/feats/starship-vehicle-feat-normalization-hooks.js";
import { registerStarshipVehicleRuntimePatches } from "/systems/foundryvtt-swse/scripts/engine/feats/starship-vehicle-runtime-patches.js";
import { registerAttackNegationFeatNormalizationHooks } from "/systems/foundryvtt-swse/scripts/engine/feats/attack-negation-feat-normalization-hooks.js";
import { registerAttackNegationRuntimePatches } from "/systems/foundryvtt-swse/scripts/engine/feats/attack-negation-runtime-patches.js";
import { registerCombatMobilityPowerFeatNormalizationHooks } from "/systems/foundryvtt-swse/scripts/engine/feats/combat-mobility-power-feat-normalization-hooks.js";
import { registerCombatMobilityPowerRuntimePatches } from "/systems/foundryvtt-swse/scripts/engine/feats/combat-mobility-power-runtime-patches.js";
import { registerAidAnotherActionAdapter } from "/systems/foundryvtt-swse/scripts/engine/combat/aid-another-action-adapter.js";
import { registerForceScoundrelCombatFeatNormalizationHooks } from "/systems/foundryvtt-swse/scripts/engine/feats/force-scoundrel-combat-feat-normalization-hooks.js";
import { registerForceScoundrelCombatRuntimePatches } from "/systems/foundryvtt-swse/scripts/engine/feats/force-scoundrel-combat-runtime-patches.js";
import { registerLegacyCloneCombatFeatNormalizationHooks } from "/systems/foundryvtt-swse/scripts/engine/feats/legacy-clone-combat-feat-normalization-hooks.js";
import { registerLegacyCloneCombatRuntimePatches } from "/systems/foundryvtt-swse/scripts/engine/feats/legacy-clone-combat-runtime-patches.js";
import { registerReturnFireFeatNormalizationHooks } from "/systems/foundryvtt-swse/scripts/engine/feats/return-fire-feat-normalization-hooks.js";
import { registerReturnFireRuntimePatches } from "/systems/foundryvtt-swse/scripts/engine/feats/return-fire-runtime-patches.js";
import { registerRebellionCombatFeatNormalizationHooks } from "/systems/foundryvtt-swse/scripts/engine/feats/rebellion-combat-feat-normalization-hooks.js";
import { registerRebellionCombatRuntimePatches } from "/systems/foundryvtt-swse/scripts/engine/feats/rebellion-combat-runtime-patches.js";
import { registerDroidCombatActionAdapter } from "/systems/foundryvtt-swse/scripts/engine/combat/droid-combat-action-adapter.js";
import { registerDroidCombatFeatNormalizationHooks } from "/systems/foundryvtt-swse/scripts/engine/feats/droid-combat-feat-normalization-hooks.js";
import { registerDroidCombatRuntimePatches } from "/systems/foundryvtt-swse/scripts/engine/feats/droid-combat-runtime-patches.js";
import { registerGalaxyIntrigueCombatActionAdapter } from "/systems/foundryvtt-swse/scripts/engine/combat/galaxy-intrigue-combat-action-adapter.js";
import { registerGalaxyIntrigueCombatFeatNormalizationHooks } from "/systems/foundryvtt-swse/scripts/engine/feats/galaxy-intrigue-combat-feat-normalization-hooks.js";
import { registerGalaxyIntrigueCombatRuntimePatches } from "/systems/foundryvtt-swse/scripts/engine/feats/galaxy-intrigue-combat-runtime-patches.js";
import { registerUnknownRegionsCombatActionAdapter } from "/systems/foundryvtt-swse/scripts/engine/combat/unknown-regions-combat-action-adapter.js";
import { registerUnknownRegionsCombatFeatNormalizationHooks } from "/systems/foundryvtt-swse/scripts/engine/feats/unknown-regions-combat-feat-normalization-hooks.js";
import { registerUnknownRegionsCombatRuntimePatches } from "/systems/foundryvtt-swse/scripts/engine/feats/unknown-regions-combat-runtime-patches.js";

export function registerInitHooks() {
    SWSELogger.log('Registering SWSE hook categories');
    registerCombatHooks();
    registerActorHooks();
    registerUIHooks();
    HooksRegistry.activateAll();
    SWSELogger.log('SWSE Hooks activated');

    Hooks.once('ready', async function() {
        if (MobileMode?.init) MobileMode.init(); else SWSELogger.warn('Mobile Mode system not available');
        registerMobilePrompt(isMobileCandidate);
        LightsaberLightSync.registerAutoSyncHooks();
        registerRerollListeners();
        FeatActionListeners.initialize();
        registerAidAnotherActionAdapter();
        registerDroidCombatActionAdapter();
        registerGalaxyIntrigueCombatActionAdapter();
        registerUnknownRegionsCombatActionAdapter();
        registerAbilityMetaSchemaDefaultHooks();
        registerGrappleFeatNormalizationHooks();
        registerGrappleFeatActions();
        registerGrappleRuntimePatches();
        registerRiflemasterNormalizationHooks();
        registerRiflemasterRuntimePatches();
        registerPistoleerNormalizationHooks();
        registerPistoleerRuntimePatches();
        registerSniperNormalizationHooks();
        registerSniperRuntimePatches();
        registerDualWeaponMasteryNormalizationHooks();
        registerDualWieldRuntimePatches();
        registerCoreCombatReactionNormalizationHooks();
        registerCoreCombatReactionRuntimePatches();
        registerCoreAttackOptionNormalizationHooks();
        registerCoreAttackOptionRuntimePatches();
        registerRageFeatNormalizationHooks();
        registerAreaExplosivesFeatNormalizationHooks();
        registerAreaExplosivesRuntimePatches();
        registerMobilityPositioningFeatNormalizationHooks();
        registerMobilityPositioningRuntimePatches();
        registerDefenseAvoidanceFeatNormalizationHooks();
        registerDefenseAvoidanceRuntimePatches();
        registerActionSpeedRuntimePatches();
        registerAttackOptionsFeatNormalizationHooks();
        registerMeleeCloseCombatFeatNormalizationHooks();
        registerRangedCombatFeatNormalizationHooks();
        registerDamageThresholdFeatNormalizationHooks();
        registerCombatFeatDamageRuntimePatches();
        registerWeaponArmorRiderNormalizationHooks();
        registerWeaponArmorRiderRuntimePatches();
        registerMartialArtsFeatNormalizationHooks();
        registerUnarmedStyleFeatNormalizationHooks();
        registerWeaponFoundationFeatNormalizationHooks();
        registerUnknownRegionsWeaponFeatNormalizationHooks();
        registerWeaponCriticalFeatNormalizationHooks();
        registerWeaponAutofireFeatNormalizationHooks();
        registerWeaponAutofireRiderRuntimePatches();
        registerWeaponLeftoverFeatNormalizationHooks();
        registerWeaponMissRiderRuntimePatches();
        registerSportHunterNormalizationHooks();
        registerSportHunterRuntimePatches();
        registerRemainingWeaponArmorFeatNormalizationHooks();
        registerRelentlessAttackRuntimePatches();
        registerStarshipVehicleFeatNormalizationHooks();
        registerStarshipVehicleRuntimePatches();
        registerAttackNegationFeatNormalizationHooks();
        registerAttackNegationRuntimePatches();
        registerCombatMobilityPowerFeatNormalizationHooks();
        registerCombatMobilityPowerRuntimePatches();
        registerForceScoundrelCombatFeatNormalizationHooks();
        registerForceScoundrelCombatRuntimePatches();
        registerLegacyCloneCombatFeatNormalizationHooks();
        registerLegacyCloneCombatRuntimePatches();
        registerReturnFireFeatNormalizationHooks();
        registerReturnFireRuntimePatches();
        registerRebellionCombatFeatNormalizationHooks();
        registerRebellionCombatRuntimePatches();
        registerDroidCombatFeatNormalizationHooks();
        registerDroidCombatRuntimePatches();
        registerGalaxyIntrigueCombatFeatNormalizationHooks();
        registerGalaxyIntrigueCombatRuntimePatches();
        registerUnknownRegionsCombatFeatNormalizationHooks();
        registerUnknownRegionsCombatRuntimePatches();
        registerSpeciesOriginFeatNormalizationHooks();
        SWSECombatActionBrowser.init();
        const stats = HooksRegistry.getStats();
        SWSELogger.log(`Hooks active: ${stats.active}/${stats.total}`);
    });
}