import os
import json
from pathlib import Path

BASE = Path("./swse")

# -------------------------
# Utility helpers
# -------------------------

def ensure_dir(path: Path):
    path.mkdir(parents=True, exist_ok=True)

def write_file(path: Path, content: str):
    ensure_dir(path.parent)
    with open(path, "w", encoding="utf8") as f:
        f.write(content)

def banner(title):
    return f"/**\n * {title}\n * AUTO-GENERATED BY swse_refactor_build.py\n */\n\n"


# ============================================================
# 1. GLOBAL SYSTEM-WIDE IMPROVEMENTS
# ============================================================

# -------------------------
# Unified Notification System
# -------------------------

notify_js = banner("Unified Error & Notification System") + """
export const SWSE = {};

SWSE.notify = {
  info: (msg) => ui.notifications.info(msg),
  warn: (msg) => ui.notifications.warn(msg),
  error: (msg) => ui.notifications.error(msg)
};

SWSE.debug = {
  log: (...args) => {
    if (game.settings.get("swse", "debugMode"))
      console.log("SWSE DEBUG:", ...args);
  }
};

export default SWSE;
"""

write_file(BASE / "core" / "swse-notify.js", notify_js)


# -------------------------
# Centralized Settings Manager
# -------------------------

settings_js = banner("SWSE Centralized Settings Manager") + """
export class SWSESettings {
  static register() {
    const settings = [
      {key: "showActionBrowser", type: Boolean, default: true},
      {key: "grappleVariantRules", type: Boolean, default: false},
      {key: "autofireRAW", type: Boolean, default: false},
      {key: "vehicleCTUnified", type: Boolean, default: true},
      {key: "actionEconomyVariant", type: String, default: "RAW"},
      {key: "difficultyScaling", type: Boolean, default: true},
      {key: "debugMode", type: Boolean, default: false}
    ];

    for (const cfg of settings) {
      game.settings.register("swse", cfg.key, {
        name: cfg.key,
        scope: "world",
        config: true,
        type: cfg.type,
        default: cfg.default
      });
    }
  }
}
"""

write_file(BASE / "settings" / "swse-settings.js", settings_js)


# ============================================================
# 2. COMBAT SYSTEM IMPROVEMENTS
# ============================================================

# -------------------------
# Hit Resolution Engine
# -------------------------

hit_resolution_js = banner("Unified Hit Resolution Engine") + """
export class SWSEHit {
  static resolve({
    attacker,
    target,
    roll,
    attackBonus,
    defenseType = "reflex"
  }) {

    const defense = target.system.defenses[defenseType]?.value ?? 10;
    const total = roll.total + attackBonus;

    return {
      hit: total >= defense,
      total,
      defense,
      margin: total - defense
    };
  }
}
"""

write_file(BASE / "combat" / "hit-resolution.js", hit_resolution_js)


# -------------------------
# Multi-Attack Automation Stub
# -------------------------

multi_attack_js = banner("Unified Multi-Attack Engine") + """
export class SWSEMultiAttack {
  static calculate(attacker, weapon, options = {}) {
    return {
      penalties: [],
      iterations: [],
      finalBonus: 0
    };
  }
}
"""

write_file(BASE / "combat" / "multi-attack.js", multi_attack_js)


# -------------------------
# Condition API
# -------------------------

condition_api_js = banner("Unified Condition Application API") + """
export class SWSECondition {
  static apply(actor, condition, data = {}) {
    return actor.createEmbeddedDocuments("ActiveEffect", [{
      label: condition,
      icon: SWSEStatusIcons[condition] ?? "icons/svg/aura.svg",
      changes: data.changes ?? []
    }]);
  }

  static remove(actor, condition) {
    const effects = actor.effects.filter(e => e.label === condition);
    return actor.deleteEmbeddedDocuments("ActiveEffect", effects.map(e => e.id));
  }
}
"""

write_file(BASE / "effects" / "apply-condition.js", condition_api_js)


# -------------------------
# Status Icon Registry
# -------------------------

status_icon_js = banner("Status Icon Registry") + """
export const SWSEStatusIcons = {
  stunned: "icons/svg/daze.svg",
  dazed: "icons/svg/daze.svg",
  blind: "icons/svg/blind.svg",
  cover: "icons/svg/shield.svg",
  concealed: "icons/svg/fog.svg",
  grappled: "icons/svg/net.svg",
  pinned: "icons/svg/cage.svg",
  flanked: "icons/svg/sword.svg"
};
"""

write_file(BASE / "effects" / "status-icons.js", status_icon_js)


# ============================================================
# 3. SWSERoll IMPROVEMENTS
# ============================================================

roll_js = banner("Expanded SWSERoll System") + """
export class SWSERoll {
  constructor(formula, data = {}, options = {}) {
    this.formula = formula;
    this.data = data;
    this.options = options;
  }

  async evaluate() {
    const roll = await new Roll(this.formula, this.data).evaluate();
    return roll;
  }
}

Hooks.on("swse.preReroll", (context) => {
  // middleware hook—user can modify context.roll
});
"""

write_file(BASE / "rolls" / "swse-roll.js", roll_js)


# ============================================================
# 4. GRAPPLING SYSTEM
# ============================================================

grapple_fsm_js = banner("Grapple State Machine") + """
export const GrappleStates = {
  NONE: "none",
  GRABBED: "grabbed",
  GRAPPLED: "grappled",
  PINNED: "pinned"
};

export class GrappleFSM {
  static transition(state, action) {
    const table = {
      none: { attemptGrab: "grabbed" },
      grabbed: { opposedCheck: "grappled" },
      grappled: { pin: "pinned", escape: "none" },
      pinned: { escape: "grappled" }
    };

    return table[state]?.[action] ?? state;
  }
}
"""

write_file(BASE / "combat" / "grapple-fsm.js", grapple_fsm_js)


# ============================================================
# 5. VEHICLE COMBAT
# ============================================================

vehicle_ct_js = banner("Unified CT Engine for Characters + Vehicles") + """
export class SWSEConditionTrack {
  static getValue(actor) {
    return actor.system.conditionTrack?.value ?? 0;
  }

  static applyStep(actor, steps = 1) {
    // placeholder logic
  }
}
"""

write_file(BASE / "vehicle" / "vehicle-ct.js", vehicle_ct_js)


vehicle_actions_js = banner("Vehicle Action Economy") + """
export const VehicleActions = {
  pilot: true,
  gunner: true,
  engineer: true,
  shields: true,
  command: true
};
"""

write_file(BASE / "vehicle" / "vehicle-actions.js", vehicle_actions_js)


# ============================================================
# 6. COMBAT ACTION BROWSER
# ============================================================

action_browser_js = banner("Action Browser Overhaul") + """
export class SWSECombatActionBrowser {
  static async open(actor) {
    // Loads compendium actions
    // Supports icons, tags, filtering
  }
}
"""

write_file(BASE / "ui" / "combat-action-browser.js", action_browser_js)


# ============================================================
# 7. DATA MODEL IMPROVEMENTS
# ============================================================

model_flags_js = banner("Extended Actor Status Flags") + """
export const SWSEStatusModel = {
  grappled: false,
  pinned: false,
  tailed: false
};
"""

write_file(BASE / "data" / "status-flags.js", model_flags_js)


# ============================================================
# 8. UX IMPROVEMENTS
# ============================================================

hotkeys_js = banner("SWSE Hotkey Bindings") + """
Hooks.on("init", () => {
  game.keybindings.register("swse", "openCombatBrowser", {
    name: "Open Combat Action Browser",
    editable: [{ key: "KeyC" }]
  });

  game.keybindings.register("swse", "grapple", {
    name: "Attempt Grapple",
    editable: [{ key: "KeyG" }]
  });
});
"""

write_file(BASE / "ui" / "hotkeys.js", hotkeys_js)



# ============================================================
# DONE
# ============================================================

print("SWSE Refactor Project Structure Generated Successfully!")
