
import { buildSurveyDefinition } from '../definition-builder.js';

function mergeBiasLayers(archetypes, scalar = 1) {
  const out = { mechanicalBias: {}, roleBias: {}, attributeBias: {} };
  for (const archetype of archetypes || []) {
    for (const layer of ['mechanicalBias', 'roleBias', 'attributeBias']) {
      for (const [key, value] of Object.entries(archetype?.[layer] || {})) {
        const normalizedKey = layer === 'attributeBias'
          ? ({ str:'strength', dex:'dexterity', con:'constitution', int:'intelligence', wis:'wisdom', cha:'charisma' }[key] || key)
          : key;
        out[layer][normalizedKey] = (out[layer][normalizedKey] || 0) + (Number(value || 0) * scalar);
      }
    }
  }
  return out;
}
const answer = (d) => d;
const archetypes = [
  { id:'mobile_skirmisher', name:'Skirmisher', notes:'Fast-moving scout who survives by position, pace, and staying difficult to pin down.', mechanicalBias:{ accuracy:2, evasion:3, mobility:3 }, roleBias:{ skirmisher:3, striker:1 }, attributeBias:{ dex:3, wis:1, con:1 } },
  { id:'wilderness_survivalist', name:'Survivalist', notes:'Fieldwise scout built around endurance, navigation, and staying alive where others fail.', mechanicalBias:{ endurancePlan:3, tacticalAwareness:2 }, roleBias:{ utility:3, support:1 }, attributeBias:{ wis:2, con:2, int:1 } },
  { id:'recon_sniper', name:'Sniper', notes:'Patient scout specializing in observation, target selection, and ending threats at range.', mechanicalBias:{ accuracy:3, critRange:2, singleTargetDamage:3 }, roleBias:{ striker:3 }, attributeBias:{ dex:3, wis:1, int:1 } },
  { id:'condition_harrier', name:'Ranger', notes:'Persistent hunter who keeps pressure on targets and wears them down over time.', mechanicalBias:{ conditionTrack:3, mobility:2, accuracy:1 }, roleBias:{ skirmisher:2, controller:1 }, attributeBias:{ wis:2, dex:2, con:1 } },
  { id:'pilot_operative', name:'Pilot', notes:'Vehicle-forward scout who values speed, approach vectors, and never being where the enemy expected.', mechanicalBias:{ initiative:2, mobility:3, vehicularControl:3 }, roleBias:{ skirmisher:2, utility:1 }, attributeBias:{ dex:3, int:1, wis:1 } }
];
const q1 = { id:'q1_operator_type', text:'What kind of operator are you?', options: archetypes.map((entry)=>answer({ id:entry.id, label:entry.name, detailRailTitle:entry.name, detailRailText:entry.notes, detailTags:[entry.name,'Scout'], archetypeHint:entry.id, biasLayers:mergeBiasLayers([entry],0.24), biases:{ archetype:entry.id } })) };
const q2 = { id:'q2_first_instinct', text:'What\'s your first instinct when the blaster bolts start flying?', options:[
  answer({ id:'staying_mobile', label:'Staying mobile', detailRailTitle:'Stay Mobile', detailRailText:'You trust movement, positioning, and refusing to stay where the fire is thickest.', detailTags:['Mobility','Evasion','Positioning','Initiative'], biasLayers:{ mechanicalBias:{ evasion:2, mobility:2, initiative:1 }, roleBias:{ skirmisher:2 }, attributeBias:{ dexterity:2, wisdom:1 } }, biases:{ skillBias:['initiative','jump','climb'], talentBias:['mobility','evasion'], featBias:['mobility','improved_initiative'] } }),
  answer({ id:'staying_stealthy', label:'Staying stealthy', detailRailTitle:'Stay Stealthy', detailRailText:'You keep the attention off yourself and let the enemy wonder where the shot came from.', detailTags:['Stealth','Ambush','Patience','Evasion'], biasLayers:{ mechanicalBias:{ tacticalAwareness:1, evasion:1 }, roleBias:{ skirmisher:1, utility:1 }, attributeBias:{ dexterity:2, wisdom:1 } }, biases:{ skillBias:['stealth','survival','perception'], talentBias:['stealth','tracking'], featBias:['stealth','precision'] } }),
  answer({ id:'using_precision', label:'Using precision', detailRailTitle:'Use Precision', detailRailText:'You prefer to remove the most valuable target clean and early.', detailTags:['Accuracy','Target Selection','Control','Discipline'], biasLayers:{ mechanicalBias:{ accuracy:2, singleTargetDamage:2, critRange:1 }, roleBias:{ striker:2 }, attributeBias:{ dexterity:2, wisdom:1 } }, biases:{ skillBias:['perception','initiative','stealth'], talentBias:['precision','sniper'], featBias:['deadeye','precise_shot'] } }),
  answer({ id:'relying_on_gear', label:'Relying on your gear', detailRailTitle:'Rely on Your Gear', detailRailText:'You trust preparation, equipment, and knowing what your kit can survive.', detailTags:['Equipment','Preparation','Mechanics','Endurance'], biasLayers:{ mechanicalBias:{ skillUtility:2, endurancePlan:1 }, roleBias:{ utility:2 }, attributeBias:{ intelligence:1, constitution:1, wisdom:1 } }, biases:{ skillBias:['mechanics','endurance','knowledge'], talentBias:['gear','utility'], featBias:['utility','equipment'] } }),
  answer({ id:'keeping_your_wits', label:'Keeping your wits about you', detailRailTitle:'Keep Your Wits', detailRailText:'You trust awareness, composure, and the ability to read the whole mess before it turns worse.', detailTags:['Awareness','Composure','Adaptability','Survival'], biasLayers:{ mechanicalBias:{ tacticalAwareness:2, initiative:1 }, roleBias:{ utility:2 }, attributeBias:{ wisdom:2, intelligence:1 } }, biases:{ skillBias:['perception','survival','knowledge'], talentBias:['awareness','survival'], featBias:['awareness','utility'] } })
]};
const q3 = { id:'q3_field_expertise', text:'What kind of work made you useful?', options:[
  answer({ id:'hunting', label:'Hunting', detailRailTitle:'Hunting', detailRailText:'You learned patience, tracking, and how to put something down clean before it ever reached you.', detailTags:['Survival','Stealth','Perception','Precision'], biasLayers:{ mechanicalBias:{ tacticalAwareness:2, accuracy:1 }, roleBias:{ utility:1, striker:1 }, attributeBias:{ wisdom:1, dexterity:1 } }, biases:{ skillBias:['survival','stealth','perception'], prestigeBias:['bounty_hunter','pathfinder'] } }),
  answer({ id:'frontier_repair', label:'Frontier repair', detailRailTitle:'Frontier Repair', detailRailText:'You learned how to keep gear alive when replacement parts and proper tools were nowhere in sight.', detailTags:['Mechanics','Endurance','Problem Solving','Equipment'], biasLayers:{ mechanicalBias:{ skillUtility:2, endurancePlan:1 }, roleBias:{ utility:2 }, attributeBias:{ intelligence:2, constitution:1 } }, biases:{ skillBias:['mechanics','knowledge','endurance'], prestigeBias:['improviser','saboteur'] } }),
  answer({ id:'trail_guiding', label:'Trail guiding', detailRailTitle:'Trail Guiding', detailRailText:'You learned how to move people through bad ground, bad weather, and worse decisions without losing them.', detailTags:['Survival','Perception','Ride','Navigation'], biasLayers:{ mechanicalBias:{ tacticalAwareness:2 }, roleBias:{ support:1, utility:1 }, attributeBias:{ wisdom:2, charisma:1 } }, biases:{ skillBias:['survival','perception','ride'], prestigeBias:['pathfinder'] } }),
  answer({ id:'search_and_rescue', label:'Search and rescue', detailRailTitle:'Search and Rescue', detailRailText:'You learned how to keep moving when others were exhausted, hurt, lost, or ready to give up.', detailTags:['Endurance','Climb','Swim','Survival'], biasLayers:{ mechanicalBias:{ endurancePlan:2 }, roleBias:{ support:1 }, attributeBias:{ constitution:2, wisdom:1 } }, biases:{ skillBias:['endurance','climb','swim','survival'], prestigeBias:['vanguard','pathfinder'] } }),
  answer({ id:'surveying', label:'Surveying', detailRailTitle:'Surveying', detailRailText:'You learned how to read land, distances, patterns, and the things other people miss when they think a place is empty.', detailTags:['Knowledge','Perception','Survival','Observation'], biasLayers:{ mechanicalBias:{ tacticalAwareness:2, skillUtility:1 }, roleBias:{ utility:2 }, attributeBias:{ intelligence:1, wisdom:2 } }, biases:{ skillBias:['knowledge','perception','survival'], prestigeBias:['pathfinder','vanguard'] } }),
  answer({ id:'courier_runs', label:'Courier runs', detailRailTitle:'Courier Runs', detailRailText:'You learned how to stay ahead of trouble, keep moving, and get where you needed to be before someone decided otherwise.', detailTags:['Pilot','Ride','Initiative','Mobility'], biasLayers:{ mechanicalBias:{ mobility:2, initiative:1 }, roleBias:{ skirmisher:1, utility:1 }, attributeBias:{ dexterity:2, wisdom:1 } }, biases:{ skillBias:['pilot','ride','initiative'], prestigeBias:['pathfinder','improviser','bounty_hunter'] } }),
  answer({ id:'beast_handling', label:'Beast handling', detailRailTitle:'Beast Handling', detailRailText:'You learned how to read animals, calm them, push them, and survive beside them when machines were not an option.', detailTags:['Ride','Survival','Perception','Patience'], biasLayers:{ mechanicalBias:{ tacticalAwareness:1, endurancePlan:1 }, roleBias:{ utility:1 }, attributeBias:{ wisdom:2 } }, biases:{ skillBias:['ride','survival','perception'], prestigeBias:['pathfinder','vanguard'] } })
]};
const q4 = { id:'q4_future_gig', text:'What sort of gig are you angling for after this?', options:[
  answer({ id:'new_worlds', label:'New worlds', detailRailTitle:'Pathfinder', detailRailText:'You want to push into the unknown, map what is unmapped, and survive where nobody has already made the path easy.', detailTags:['Exploration','Navigation','Survival','Discovery'], biasLayers:{ mechanicalBias:{ tacticalAwareness:2, mobility:1 }, roleBias:{ utility:2 }, attributeBias:{ wisdom:1, dexterity:1 } }, biases:{ prestigeBias:['pathfinder'] } }),
  answer({ id:'hunting_criminals', label:'Hunting criminals', detailRailTitle:'Bounty Hunter', detailRailText:'You want to track dangerous people down, corner them, and make sure they do not slip away.', detailTags:['Tracking','Pursuit','Precision','Capture'], biasLayers:{ mechanicalBias:{ accuracy:1, singleTargetDamage:1 }, roleBias:{ striker:1, utility:1 }, attributeBias:{ dexterity:1, wisdom:1 } }, biases:{ prestigeBias:['bounty_hunter'] } }),
  answer({ id:'upholding_the_law', label:'Upholding the law', detailRailTitle:'Enforcer', detailRailText:'You want to bring order through pressure, field authority, and practical force.', detailTags:['Authority','Control','Discipline','Pursuit'], biasLayers:{ mechanicalBias:{ conditionTrack:1, initiative:1 }, roleBias:{ controller:1 }, attributeBias:{ constitution:1, wisdom:1 } }, biases:{ prestigeBias:['enforcer'] } }),
  answer({ id:'going_undercover', label:'Going undercover', detailRailTitle:'Infiltrator', detailRailText:'You want to win by getting close, staying unnoticed, and striking from the position nobody expected.', detailTags:['Stealth','Deception','Infiltration','Patience'], biasLayers:{ mechanicalBias:{ tacticalAwareness:1, skillUtility:1 }, roleBias:{ utility:1 }, attributeBias:{ dexterity:1, intelligence:1, wisdom:1 } }, biases:{ prestigeBias:['infiltrator'] } }),
  answer({ id:'breaking_infrastructure', label:'Breaking infrastructure', detailRailTitle:'Saboteur', detailRailText:'You want to hurt the enemy by tearing apart the systems, supply lines, and machinery they rely on.', detailTags:['Sabotage','Mechanics','Disruption','Pressure'], biasLayers:{ mechanicalBias:{ skillUtility:2, areaControl:1 }, roleBias:{ controller:1, utility:1 }, attributeBias:{ intelligence:2, dexterity:1 } }, biases:{ prestigeBias:['saboteur'] } }),
  answer({ id:'scouting_with_a_rifle', label:'Scouting with a rifle', detailRailTitle:'Vanguard', detailRailText:'You want to identify enemy positions first, mark the field, and put accurate fire where it matters most.', detailTags:['Recon','Rifle','Precision','Positioning'], biasLayers:{ mechanicalBias:{ accuracy:2, tacticalAwareness:1 }, roleBias:{ striker:1, utility:1 }, attributeBias:{ dexterity:2, wisdom:1 } }, biases:{ prestigeBias:['vanguard'] } }),
  answer({ id:'using_whatever_works', label:'Using whatever works', detailRailTitle:'Improviser', detailRailText:'You do not care what wins, only that it works. You trust adaptability over doctrine.', detailTags:['Adaptability','Utility','Resourcefulness','Survival'], biasLayers:{ mechanicalBias:{ skillUtility:2, mobility:1 }, roleBias:{ utility:2 }, attributeBias:{ intelligence:1, dexterity:1, wisdom:1 } }, biases:{ prestigeBias:['improviser'] } })
]};
const q5Branches = {
  mobile_skirmisher: [
    answer({ id:'skirmisher_1', label:'If they can pin you down, you already screwed up.', detailRailTitle:'Never Stay Still', detailRailText:'You survive by movement, angles, and refusing to be where the enemy expects.', detailTags:['Mobility','Evasion','Positioning'], biasLayers:{ mechanicalBias:{ mobility:2, evasion:1 }, roleBias:{ skirmisher:2 }, attributeBias:{ dexterity:2 } }, biases:{ skillBias:['initiative','jump','climb'], talentBias:['mobility','evasion'], featBias:['mobility','improved_initiative'] } }),
    answer({ id:'skirmisher_2', label:'Speed buys you options. Options keep you alive.', detailRailTitle:'Speed Buys Options', detailRailText:'You value pace because it keeps the situation from trapping you.', detailTags:['Speed','Adaptability','Survival'], biasLayers:{ mechanicalBias:{ mobility:2, initiative:1 }, roleBias:{ skirmisher:1, utility:1 }, attributeBias:{ dexterity:2, wisdom:1 } }, biases:{ skillBias:['initiative','pilot','jump'], talentBias:['mobility'], featBias:['mobility','vehicle'] } }),
    answer({ id:'skirmisher_3', label:'The trick is making the other guy chase the wrong problem.', detailRailTitle:'Wrong Problem', detailRailText:'You win by forcing the enemy to react to the wrong threat, at the wrong time.', detailTags:['Tempo','Misdirection','Pressure'], biasLayers:{ mechanicalBias:{ tacticalAwareness:1, mobility:1 }, roleBias:{ utility:1, skirmisher:1 }, attributeBias:{ dexterity:1, intelligence:1 } }, biases:{ skillBias:['initiative','stealth','perception'], talentBias:['mobility','misdirection'], featBias:['utility','mobility'] } }),
    answer({ id:'skirmisher_4', label:'You don\'t need a clean fight. You need a winning one.', detailRailTitle:'No Need for Clean Fights', detailRailText:'You care about results, not style, and you use movement to get them.', detailTags:['Pragmatism','Tempo','Pressure'], biasLayers:{ mechanicalBias:{ mobility:1, accuracy:1 }, roleBias:{ striker:1, skirmisher:1 }, attributeBias:{ dexterity:1, constitution:1 } }, biases:{ skillBias:['initiative','survival','climb'], talentBias:['mobility','pressure'], featBias:['mobility','utility'] } })
  ],
  wilderness_survivalist: [
    answer({ id:'survivalist_1', label:'The land tells you what kills fools.', detailRailTitle:'Read the Land', detailRailText:'You trust the ground, the weather, and the signs most people never notice.', detailTags:['Survival','Observation','Terrain'], biasLayers:{ mechanicalBias:{ tacticalAwareness:2 }, roleBias:{ utility:2 }, attributeBias:{ wisdom:2 } }, biases:{ skillBias:['survival','perception','knowledge'], talentBias:['survival','tracking'], featBias:['awareness','survival'] } }),
    answer({ id:'survivalist_2', label:'Comfort makes people careless.', detailRailTitle:'Comfort Makes People Careless', detailRailText:'You know the hard places strip weakness off people fast.', detailTags:['Endurance','Resolve','Fieldcraft'], biasLayers:{ mechanicalBias:{ endurancePlan:2 }, roleBias:{ utility:1 }, attributeBias:{ constitution:2, wisdom:1 } }, biases:{ skillBias:['endurance','survival','climb'], talentBias:['survival','endurance'], featBias:['toughness','survival'] } }),
    answer({ id:'survivalist_3', label:'If you know the ground, you already know the fight.', detailRailTitle:'Know the Ground', detailRailText:'You believe terrain decides fights before the first shot lands.', detailTags:['Terrain','Preparation','Positioning'], biasLayers:{ mechanicalBias:{ tacticalAwareness:2, mobility:1 }, roleBias:{ utility:2 }, attributeBias:{ wisdom:2, intelligence:1 } }, biases:{ skillBias:['survival','perception','ride'], talentBias:['pathfinding','awareness'], featBias:['awareness','mobility'] } }),
    answer({ id:'survivalist_4', label:'Out there, nature doesn\'t care if you were ready. You should.', detailRailTitle:'Be Ready Anyway', detailRailText:'You value preparation because the frontier won\'t make allowances for anyone.', detailTags:['Preparation','Survival','Discipline'], biasLayers:{ mechanicalBias:{ endurancePlan:1, tacticalAwareness:1 }, roleBias:{ utility:1 }, attributeBias:{ wisdom:1, constitution:1 } }, biases:{ skillBias:['survival','endurance','knowledge'], talentBias:['survival','preparation'], featBias:['survival','utility'] } })
  ],
  recon_sniper: [
    answer({ id:'sniper_1', label:'The cleanest shot is the one they never saw coming.', detailRailTitle:'Unseen Shot', detailRailText:'You value patience, setup, and ending problems before they can respond.', detailTags:['Precision','Stealth','Patience'], biasLayers:{ mechanicalBias:{ accuracy:2, critRange:1 }, roleBias:{ striker:2 }, attributeBias:{ dexterity:2, wisdom:1 } }, biases:{ skillBias:['perception','stealth','initiative'], talentBias:['precision','sniper'], featBias:['precise_shot','far_shot'] } }),
    answer({ id:'sniper_2', label:'You only get one perfect angle. Don\'t waste it.', detailRailTitle:'Perfect Angle', detailRailText:'You trust setup, sightlines, and making the first good shot matter.', detailTags:['Angle','Observation','Discipline'], biasLayers:{ mechanicalBias:{ accuracy:2, singleTargetDamage:1 }, roleBias:{ striker:2 }, attributeBias:{ dexterity:2, intelligence:1 } }, biases:{ skillBias:['perception','knowledge','stealth'], talentBias:['sniper','awareness'], featBias:['precise_shot','deadeye'] } }),
    answer({ id:'sniper_3', label:'Most fights are decided before the target knows it\'s in one.', detailRailTitle:'Decided Early', detailRailText:'You believe preparation and target selection win more fights than volume of fire.', detailTags:['Target Selection','Preparation','Precision'], biasLayers:{ mechanicalBias:{ tacticalAwareness:1, accuracy:1 }, roleBias:{ striker:1, utility:1 }, attributeBias:{ dexterity:1, wisdom:1, intelligence:1 } }, biases:{ skillBias:['perception','initiative','knowledge'], talentBias:['precision','tracking'], featBias:['improved_initiative','precise_shot'] } }),
    answer({ id:'sniper_4', label:'One round. One problem less.', detailRailTitle:'One Round, One Problem Less', detailRailText:'You are there to remove the right target cleanly and move on.', detailTags:['Lethality','Efficiency','Precision'], biasLayers:{ mechanicalBias:{ singleTargetDamage:2, accuracy:1 }, roleBias:{ striker:2 }, attributeBias:{ dexterity:2 } }, biases:{ skillBias:['perception','stealth','survival'], talentBias:['sniper','precision'], featBias:['weapon_focus_rifles','deadeye'] } })
  ],
  condition_harrier: [
    answer({ id:'ranger_1', label:'If they keep running, keep hurting them.', detailRailTitle:'Keep the Pressure On', detailRailText:'You don\'t need one perfect hit. You need pressure that never really stops.', detailTags:['Pressure','Pursuit','Wear Them Down'], biasLayers:{ mechanicalBias:{ conditionTrack:2, mobility:1 }, roleBias:{ skirmisher:1, controller:1 }, attributeBias:{ wisdom:1, dexterity:1, constitution:1 } }, biases:{ skillBias:['survival','perception','stealth'], talentBias:['tracking','harrier'], featBias:['mobility','pressure'] } }),
    answer({ id:'ranger_2', label:'A target that can\'t rest is already losing.', detailRailTitle:'No Rest for the Target', detailRailText:'You wear people down until mistakes stop being avoidable.', detailTags:['Attrition','Pressure','Patience'], biasLayers:{ mechanicalBias:{ conditionTrack:2 }, roleBias:{ controller:1 }, attributeBias:{ constitution:1, wisdom:1 } }, biases:{ skillBias:['survival','endurance','perception'], talentBias:['tracking','attrition'], featBias:['endurance','utility'] } }),
    answer({ id:'ranger_3', label:'You don\'t have to win fast if you win for sure.', detailRailTitle:'Win for Sure', detailRailText:'You value certainty, pursuit, and letting the target unravel over time.', detailTags:['Certainty','Persistence','Control'], biasLayers:{ mechanicalBias:{ conditionTrack:1, tacticalAwareness:1 }, roleBias:{ controller:1, utility:1 }, attributeBias:{ wisdom:1, constitution:1 } }, biases:{ skillBias:['perception','survival','knowledge'], talentBias:['tracking','awareness'], featBias:['utility','awareness'] } }),
    answer({ id:'ranger_4', label:'Every trail ends somewhere. I just get there first.', detailRailTitle:'Every Trail Ends Somewhere', detailRailText:'You trust pursuit, fieldcraft, and the patience to stay on a target longer than they can stay hidden.', detailTags:['Tracking','Pursuit','Fieldcraft'], biasLayers:{ mechanicalBias:{ tacticalAwareness:2 }, roleBias:{ utility:1, skirmisher:1 }, attributeBias:{ wisdom:2, dexterity:1 } }, biases:{ skillBias:['survival','perception','stealth'], talentBias:['tracking','survival'], featBias:['awareness','survival'] } })
  ],
  pilot_operative: [
    answer({ id:'pilot_1', label:'Distance is just another weapon.', detailRailTitle:'Distance as a Weapon', detailRailText:'You think in vectors, exits, and speed before anyone else has picked a direction.', detailTags:['Pilot','Mobility','Escape'], biasLayers:{ mechanicalBias:{ vehicularControl:2, mobility:1 }, roleBias:{ skirmisher:1, utility:1 }, attributeBias:{ dexterity:2, intelligence:1 } }, biases:{ skillBias:['pilot','initiative','mechanics'], talentBias:['pilot','mobility'], featBias:['vehicle','improved_initiative'] } }),
    answer({ id:'pilot_2', label:'If I can get there first, I own the terms.', detailRailTitle:'Own the Terms', detailRailText:'You trust speed and approach to decide a job before the other side can settle in.', detailTags:['Speed','Approach','Initiative'], biasLayers:{ mechanicalBias:{ initiative:2, mobility:1 }, roleBias:{ skirmisher:1 }, attributeBias:{ dexterity:2, wisdom:1 } }, biases:{ skillBias:['pilot','initiative','ride'], talentBias:['pilot','speed'], featBias:['vehicle','mobility'] } }),
    answer({ id:'pilot_3', label:'A good pilot knows when to leave and when to dive harder.', detailRailTitle:'Leave or Dive', detailRailText:'You value judgment, timing, and knowing which kind of risk is worth taking.', detailTags:['Judgment','Timing','Risk'], biasLayers:{ mechanicalBias:{ vehicularControl:1, initiative:1 }, roleBias:{ utility:1 }, attributeBias:{ dexterity:1, wisdom:1, intelligence:1 } }, biases:{ skillBias:['pilot','perception','initiative'], talentBias:['pilot','timing'], featBias:['vehicle','utility'] } }),
    answer({ id:'pilot_4', label:'Engines don\'t care about speeches. They care if you know your job.', detailRailTitle:'Know Your Job', detailRailText:'You respect competence, maintenance, and the ugly practical side of staying alive in a vehicle.', detailTags:['Mechanics','Pilot','Competence'], biasLayers:{ mechanicalBias:{ vehicularControl:2, skillUtility:1 }, roleBias:{ utility:1 }, attributeBias:{ intelligence:1, dexterity:1 } }, biases:{ skillBias:['pilot','mechanics','knowledge'], talentBias:['pilot','gear'], featBias:['vehicle','utility'] } })
  ]
};

const survey = buildSurveyDefinition({ surveyId:'L1_Scout', classId:'scout', displayName:'Scout', mentorKey:'Scout', archetypes, questions:[q1,q2,q3,q4], resolveQuestions(answers={}) { const selected = answers?.[q1.id]?.id; return [q1,q2,q3,q4,{ id:'q5_identity_statement', text:'Which one sounds most like you?', options:q5Branches[selected] || [] }]; } });

export default survey;
