import assert from 'node:assert/strict';
import { buildGmDatapadActionRegistry, unresolvedControls, SURFACES } from '../scripts/dev/gm-datapad-action-registry.mjs';

// GM Datapad recovery — action-integrity contract.
//
// Foundry's ApplicationV2 + global surface cannot be constructed under this
// repo's Node test harness (same limitation as tests/phase4-sheet-architecture-contract.test.mjs
// and tests/phase5-sheet-action-integrity-contract.test.mjs), so this is a
// source-text contract test: it derives, by scanning each registered GM
// Datapad surface's template tree (scripts/dev/gm-datapad-action-registry.mjs
// — not a hand-maintained control list), every control rendered on that
// surface, and proves it reaches a real handler at one of three levels:
//
//   - ACTION-VALUE-LEVEL, for attributes that dispatch on a LITERAL,
//     template-authored value (data-gm-faction-action, data-location-action,
//     data-intel-action, data-economy-action, data-skill-challenge-action,
//     bare data-action on store/bulletin/approvals, data-gm-v2-action): the
//     exact rendered value must appear as a real branch (switch/case,
//     `=== 'x'`, or a `[data-x="value"]` literal selector) in the file(s)
//     that actually own that dispatch — including multi-hop forwarding,
//     e.g. data-economy-action -> GMDatapad._handleEconomyRepairAction ->
//     HolonetMessengerService.threadAction's own switch.
//   - DYNAMIC-ACTION-VALUE-LEVEL, for the one attribute whose template value
//     is itself a Handlebars expression rather than a literal
//     (data-trade-action="{{this.action}}" in trade-board.hbs, generated by
//     GMTradeConsoleSurfaceService._buildActions()): the scanner statically
//     derives the actual generated vocabulary from that service's source
//     (its frozen TRANSFER_TYPES config plus its own hardcoded gm-*-trade
//     literals) and proves every value it can produce is accepted by
//     HolonetMessengerService's dispatch — scoped specifically to that
//     switch block, not a whole-file scan (see the "unresolved" regression
//     assertion below for why that distinction matters).
//   - ATTRIBUTE-NAME-LEVEL, for everything else (ids/refs, tab/subtab
//     switches whose vocabulary is validated against sibling template
//     attributes rather than hardcoded strings, surface-id navigation
//     validated against the surface registry): the attribute name must have
//     a `dataset.<name>` read somewhere in the files allowed to wire that
//     surface.
//
// This MUST fail when a new data-attribute (or a new literal/derived value
// of a dispatch attribute) is added to a live GM Datapad template with no
// matching wiring anywhere the scanner looks, without a matching allowlist
// entry in gm-datapad-action-registry.mjs.

const surfaces = await buildGmDatapadActionRegistry();

// 14 registered surfaces + the shared host-chrome entry (sidebar/dock/toolbar
// partials included directly from gm-datapad.hbs, outside any surface's own
// template tree, so they need a scan entry of their own).
assert.equal(Object.keys(surfaces).length, 15, 'expected all 14 registered GM Datapad surfaces plus the host-chrome entry to be scanned');

for (const surfaceId of Object.keys(SURFACES)) {
  const surface = surfaces[surfaceId];
  assert.ok(surface, `expected surface "${surfaceId}" in the registry`);
  assert.ok(surface.templateFiles.length > 0, `surface "${surfaceId}" resolved no templates — has its root template moved?`);
}
assert.ok(surfaces.host.templateFiles.length > 0, 'expected the host-chrome entry to resolve the sidebar/dock/toolbar partials');

const unresolved = unresolvedControls(surfaces);
assert.equal(
  unresolved.length,
  0,
  `Found ${unresolved.length} rendered GM Datapad control(s) with no reachable handler:\n` +
  unresolved.map(u => `  [${u.surfaceId}] ${u.attribute}  (in: ${u.templates.join(', ')})${u.note ? `\n      ${u.note}` : ''}`).join('\n') +
  '\n\nEach one must become wired (add the matching dataset.<name> read, or the matching dispatch branch, ' +
  'to its owning controller), be declared a non-action marker in NON_ACTION_ATTRIBUTE_NAMES, or be removed ' +
  'from the template if proven dead — see docs/audits/gm-datapad-recovery-action-integrity.md.'
);

// Sanity checks: known always-live controls must be present at the right
// proof level, so this test cannot silently pass by scanning zero real
// controls or by falling back to a weaker proof level for something that
// should be proven more strongly.
const jobsControls = surfaces.jobs.controls.map(c => c.attribute);
assert.ok(jobsControls.includes('data-gm-wizard-open'), 'sanity check: the Job contract wizard open control should be present in the registry');
assert.ok(jobsControls.includes('data-job-subtab-switch'), 'sanity check: the Job dossier/settlement subtab strip should be present in the registry');

const factionsControls = surfaces.factions.controls;
const approveSuggestion = factionsControls.find(c => c.attribute === 'data-gm-faction-action="approve-suggestion"');
assert.ok(approveSuggestion, 'sanity check: data-gm-faction-action="approve-suggestion" should be scanned at action-value level');
assert.equal(approveSuggestion.proof, 'action-value', 'approve-suggestion must be proven at action-value level, not merely attribute-name level');
assert.equal(approveSuggestion.status, 'ACTION_VALUE_HANDLED');

for (const record of ['reject-suggestion', 'remove-relationship']) {
  const entry = factionsControls.find(c => c.attribute === `data-gm-faction-action="${record}"`);
  assert.ok(entry, `sanity check: data-gm-faction-action="${record}" should be scanned at action-value level`);
  assert.equal(entry.status, 'ACTION_VALUE_HANDLED', `${record} must resolve to a real handler, not a placebo control`);
}

// data-trade-action is dynamic in the template (data-trade-action="{{this.action}}"),
// so it must never appear as an 'action-value' (literal-template) proof —
// only as 'dynamic-action-value', derived from GMTradeConsoleSurfaceService.
const tradeControls = surfaces.trade.controls;
const tradeActionEntries = tradeControls.filter(c => c.attribute.startsWith('data-trade-action='));
assert.ok(tradeActionEntries.length > 0, 'expected the derived Trade action vocabulary to produce scanned entries');
for (const entry of tradeActionEntries) {
  assert.equal(entry.proof, 'dynamic-action-value', `${entry.attribute} must be proven as dynamic-action-value, not literal action-value (its template value is a Handlebars expression, not a literal)`);
  assert.equal(entry.status, 'DYNAMIC_ACTION_SOURCE_VERIFIED', `${entry.attribute} must resolve to a verified dynamic dispatch, not a placebo or unresolved control`);
}
// The full generated Trade action vocabulary — one entry per TRANSFER_TYPES
// (credit/item/asset) *Action field plus the five hardcoded gm-*-trade
// diagnostic actions in _buildActions(). If GMTradeConsoleSurfaceService's
// action set changes, this list (and the derived count) must be updated
// deliberately, not silently.
const expectedTradeActions = [
  'approve-transfer', 'accept-transfer', 'decline-transfer', 'cancel-transfer',
  'approve-item-transfer', 'accept-item-transfer', 'accept-item-counter', 'decline-item-transfer', 'decline-item-counter', 'cancel-item-transfer',
  'approve-asset-transfer', 'approve-asset-counter', 'accept-asset-transfer', 'accept-asset-counter', 'decline-asset-transfer', 'decline-asset-counter', 'cancel-asset-transfer',
  'gm-fail-trade', 'gm-reopen-trade', 'gm-mark-trade-reconciled', 'gm-unarchive-trade', 'gm-archive-trade'
];
const tradeActionValues = tradeActionEntries.map(c => c.attribute).sort();
assert.deepEqual(
  tradeActionValues,
  expectedTradeActions.map(v => `data-trade-action="${v}" (dynamic)`).sort(),
  'the derived Trade action vocabulary must match the full expected set — if this fails after an intentional TRANSFER_TYPES/_buildActions change, update expectedTradeActions here to match'
);

// Regression guard for the over-acceptance bug found during this pass:
// holonet-messenger-service.js reuses the identifier `action` in an
// unrelated second-layer dispatcher (_gmResolveCreditTransfer). An earlier
// version of this scanner's unscoped whole-file `action === 'x'` scan kept
// matching a case label's target string even when the outer switch's own
// case for it was renamed — i.e. it could report a broken dispatch as
// handled. Prove the scanner is switch-scoped for this file by checking the
// registry module's own source for the fix, since reproducing the actual
// break here would require mutating a large shared production file.
{
  const { readFile } = await import('node:fs/promises');
  const registrySource = await readFile(new URL('../scripts/dev/gm-datapad-action-registry.mjs', import.meta.url), 'utf8');
  assert.match(
    registrySource,
    /dispatchMode:\s*'switch-only'/,
    'the Trade dynamic-dispatch source must use switch-only mode against holonet-messenger-service.js'
  );
  assert.match(
    registrySource,
    /alsoCheckMode:\s*'switch-only'/,
    'the economy-action dispatch entry\'s alsoCheck against holonet-messenger-service.js must use switch-only mode'
  );
}

const actionValueControlCount = Object.values(surfaces).reduce((n, s) => n + s.controls.filter(c => c.proof === 'action-value').length, 0);
const dynamicActionValueControlCount = Object.values(surfaces).reduce((n, s) => n + s.controls.filter(c => c.proof === 'dynamic-action-value').length, 0);
const attributeLevelControlCount = Object.values(surfaces).reduce((n, s) => n + s.controls.filter(c => c.proof === 'attribute-name').length, 0);
const totalControlCount = Object.values(surfaces).reduce((n, s) => n + s.controls.length, 0);

assert.ok(actionValueControlCount > 100, `expected a substantial share of scanned controls to be proven at action-value level (got ${actionValueControlCount})`);
assert.equal(dynamicActionValueControlCount, expectedTradeActions.length, 'dynamic-action-value proofs should currently come only from the derived Trade vocabulary');
assert.equal(totalControlCount, actionValueControlCount + dynamicActionValueControlCount + attributeLevelControlCount, 'every scanned control must be classified as exactly one of the three proof levels');

console.log(`GM Datapad action-integrity contract passed (${totalControlCount} controls across ${Object.keys(surfaces).length} entries: ${actionValueControlCount} action-value, ${dynamicActionValueControlCount} dynamic-action-value, ${attributeLevelControlCount} attribute-name, 0 unresolved).`);
