import assert from 'node:assert/strict';
import fs from 'node:fs';
import { canonicalTalentUuid, canonicalTalentId, sameTalentUuid } from '../scripts/data/talent-source-identity.js';

// Phase 3G-3: pins the migration manifest, the dry-run certification, the owner ruling and the schema decision.
const rd = rel => JSON.parse(fs.readFileSync(new URL('../' + rel, import.meta.url), 'utf8'));
const m = rd('data/audits/talent-phase-3g-migration-manifest.json'), r = rd('data/audits/talent-phase-3g-dry-run-report.json');
let n = 0; const test = (name, fn) => { fn(); n++; console.log('  ok  ' + name); };

test('manifest: 311 source-valid rows, 311 unique owner leaves, 4 false conditions removed, every target a canonical v13 UUID that exists', () => {
  assert.equal(m.rows.length, 311); assert.equal(m.removals.length, 4);
  assert.equal(new Set(m.rows.map(x => `${x.ownerId}|${x.path}`)).size, 311);
  for (const x of m.rows) { assert.equal(x.proposed.uuid, canonicalTalentUuid(x.target.id)); assert.equal(x.proposed.type, 'talent'); assert.ok(x.proposed.name); assert.ok(x.derivation.basis); }
});
test('dry-run certified: 311 leaves (5 retargeted), 4 removals, 4 text lines, every check passes', () => {
  assert.equal(r.status, 'DRY_RUN_CERTIFIED'); assert.equal(r.dryRun, true);
  assert.deepEqual([r.counts.talentLeavesMigrated, r.counts.falseConditionsRemoved, r.counts.leavesRetargeted, r.counts.prerequisiteTextLinesRestored], [311, 4, 5, 4]);
  assert.ok(r.counts.recordsChanged > 0 && r.counts.fieldLevelLeafMutations > 0); // exact counts are regenerated by the tool, never pinned here
  assert.ok(r.verification.results.every(x => x.ok));
  const e = r.runtimeEffectiveness;
  assert.deepEqual([e.embeddedSourceLinked, e.embeddedLegacyLinkForm, e.pending, e.viaUuidEmbedded, e.viaUuidPending, e.failures.length], [311, 311, 311, 311, 311, 0]);
  assert.equal(e.wrongSameNameChecked, e.wrongSameNameRejected); assert.equal(e.unlinkedWrongTreeChecked, e.unlinkedWrongTreeRejected);
});
test('owner ruling: Find an Opening -> Scum and Villainy|Outlaw|Seize the Moment (e19c06b6dfc7a703), NOT Provocateur', () => {
  const x = m.rows.find(y => y.ownerName === 'Find an Opening');
  assert.equal(x.ownerCanonicalIdentity, 'Scum and Villainy|Outlaw|Find an Opening');
  assert.equal(x.target.canonicalIdentity, 'Scum and Villainy|Outlaw|Seize the Moment');
  assert.equal(x.target.id, 'e19c06b6dfc7a703'); assert.equal(x.target.uuid, 'Compendium.foundryvtt-swse.talents.Item.e19c06b6dfc7a703');
  assert.equal(x.target.tree, 'Outlaw'); assert.match(x.derivation.basis, /OWNER_RULING/);
});
test('the five Phase 3D repairs migrate their existing production ids to UUIDs', () => {
  for (const nm of ['Fearsome', 'Ruthless Negotiator', 'Shared Notoriety', 'Unsavory Reputation', 'Weakening Strike']) {
    const x = m.rows.find(y => y.ownerName === nm && y.existing.id === y.target.id); assert.ok(x, nm); assert.match(x.derivation.basis, /Phase 3D repair/);
  }
});
test('schema decision: uuid authoritative, name retained as label, id removed', () => {
  assert.match(m.schemaDecision.uuid, /authoritative/); assert.match(m.schemaDecision.name, /retained/); assert.match(m.schemaDecision.id, /REMOVED/);
});
test('helper accepts the nine legacy 32-hex production ids in every form', () => {
  const id = 'eb4f3e8660bc476589d0323d4cc00845';
  assert.equal(canonicalTalentId(id), id); assert.equal(canonicalTalentUuid(`Compendium.foundryvtt-swse.talents.${id}`), `Compendium.foundryvtt-swse.talents.Item.${id}`);
  assert.ok(sameTalentUuid(id, `Compendium.foundryvtt-swse.talents.Item.${id}`));
  assert.ok(m.rows.some(x => x.target.id === id));
});
test('source rulings: four false conditions removed (container dropped), five retargets, four prerequisite texts restored', () => {
  assert.deepEqual(m.removals.map(x => x.ownerId).sort(), ['7aa4ca13a96d8770', 'b7d5a1bc3d40b964', 'd9e707f23fffc2af', 'e19c06b6dfc7a703']);
  const rt = m.rows.filter(x => x.derivation.basis === 'SOURCE_RULING_RETARGET');
  assert.deepEqual(rt.map(x => x.ownerName).sort(), ['Dumb Luck', 'Ricochet Shot', 'Stay in the Fight', 'Uncanny Luck', 'Unlikely Shot']);
  for (const x of rt) assert.equal(x.target.uuid, x.ownerName === 'Stay in the Fight' ? 'Compendium.foundryvtt-swse.talents.Item.d9ffff2586cd259b' : 'Compendium.foundryvtt-swse.talents.Item.5fbf1a3504865fba');
  assert.deepEqual(m.textCorrections.map(c => [c.name, c.after.prerequisites]).sort(), [['Force Haze', 'Clear Mind'], ['Sow Confusion', 'Hesitate'], ['Starship Raider', 'Spacehound'], ['Swift Power', 'Power of the Dark Side']]);
  const sc = rd('data/audits/talent-phase-3g-source-corrections.json'); assert.equal(sc.entries.length, 4); assert.ok(sc.entries.every(e => e.verification.status === 'PDF_VERIFIED' && e.fields.join() === 'prerequisites'));
});
console.log(`talent-phase-3g-dry-run: ${n} checks passed`);
