
// ======================================================================
// TalentNode.js
// Represents a normalized, prerequisite-enriched talent node.
// ======================================================================

export class TalentNode {
  constructor(talentDocument) {
    this.id = talentDocument.id;
    this.name = talentDocument.name;
    this.tree = talentDocument.system?.talent_tree ?? 'Unknown';

    // Raw prerequisite string
    this.rawPrereq = talentDocument.system?.prerequisites ?? '';

    // Structured prerequisite array (generated by PrerequisiteEnricher)
    this.prereq = [];

    // Forward and backward edges for graph traversal
    this.requires = new Set();   // talents THIS one depends on
    this.unlocks = new Set();    // talents that depend on THIS one
  }

  addRequirement(talentId) {
    this.requires.add(talentId);
  }

  addUnlock(talentId) {
    this.unlocks.add(talentId);
  }

  toJSON() {
    return {
      id: this.id,
      name: this.name,
      tree: this.tree,
      rawPrereq: this.rawPrereq,
      prereq: this.prereq,
      requires: Array.from(this.requires),
      unlocks: Array.from(this.unlocks)
    };
  }
}
