import { buildSurveyDefinition } from '../definition-builder.js';

const answer = (d) => d;

const branchQuestion = {
  id: 'q5_identity_statement',
  text: 'Which of these sounds most like you?',
  branchOn: 'q1_operator_type',
  branches: {
    heavy_weapons_specialist: [
      answer({ id:'hws_1', label:"If the ground's shaking, I'm doing my job.", detailRailTitle:'Ground-Shaker', detailRailText:'You trust weight of fire and the kind of presence nobody ignores.', detailTags:['Firepower','Pressure','Heavy Weapons','Shock'], biases:{ skillBias:['initiative','mechanics'], prestigeBias:['elite_trooper','vanguard'], featBias:['heavy_weapons','autofire','suppression'], talentBias:['heavy_weapons','battlefield_pressure'] } }),
      answer({ id:'hws_2', label:'Cover is just a suggestion.', detailRailTitle:'Cover Is a Suggestion', detailRailText:'You believe the right volume of fire can make defenses meaningless.', detailTags:['Suppression','Firepower','Aggression','Control'], biases:{ skillBias:['perception','initiative'], prestigeBias:['elite_trooper'], featBias:['autofire','heavy_weapons'], talentBias:['suppression','pressure'] } }),
      answer({ id:'hws_3', label:'Make enough noise and the enemy stops thinking.', detailRailTitle:'Noise Stops Thinking', detailRailText:'You use violence to break momentum, morale, and the enemy\'s nerve.', detailTags:['Suppression','Morale Pressure','Firepower','Control'], biases:{ skillBias:['initiative','knowledgeTactics'], prestigeBias:['vanguard','elite_trooper'], featBias:['suppression','autofire'], talentBias:['pressure','control'] } }),
      answer({ id:'hws_4', label:"If I'm carrying it, I plan to use all of it.", detailRailTitle:'Use All of It', detailRailText:'You do not haul heavy weapons for show. You haul them to end things.', detailTags:['Commitment','Firepower','Endurance','Battlefield Force'], biases:{ skillBias:['endurance','mechanics'], prestigeBias:['elite_trooper'], featBias:['heavy_weapons','toughness'], talentBias:['heavy_weapons','endurance'] } })
    ],
    tank: [
      answer({ id:'tank_1', label:'I hold the ground. Others decide what to do with it.', detailRailTitle:'Hold the Ground', detailRailText:'You measure yourself by whether the line still stands when the smoke clears.', detailTags:['Defense','Endurance','Lineholding','Duty'], biases:{ skillBias:['endurance','initiative'], prestigeBias:['elite_trooper','vanguard'], featBias:['defense','toughness','armor_proficiency_heavy'], talentBias:['resilience','defense'] } }),
      answer({ id:'tank_2', label:"Pain's part of the work.", detailRailTitle:'Pain\'s Part of the Work', detailRailText:'You do not expect battle to be fair. You expect to still be standing after it isn\'t.', detailTags:['Toughness','Endurance','Resolve','Durability'], biases:{ skillBias:['endurance','treatInjury'], prestigeBias:['gladiator','elite_trooper'], featBias:['toughness','improved_damage_threshold'], talentBias:['resilience','toughness'] } }),
      answer({ id:'tank_3', label:"If they want through, they go through me.", detailRailTitle:'Through Me First', detailRailText:'You exist to be the thing the enemy cannot ignore and cannot easily remove.', detailTags:['Protection','Defense','Pressure','Sacrifice'], biases:{ skillBias:['initiative','treatInjury','endurance'], prestigeBias:['vanguard','officer'], featBias:['combat_reflexes','improved_defenses'], talentBias:['protection','control'] } }),
      answer({ id:'tank_4', label:"Armor's only useful if the person inside it keeps moving.", detailRailTitle:'Keep Moving in Armor', detailRailText:'You understand toughness as action, not passivity.', detailTags:['Armor','Mobility','Durability','Discipline'], biases:{ skillBias:['endurance','climb'], prestigeBias:['elite_trooper','gladiator'], featBias:['armor_proficiency_heavy','toughness'], talentBias:['mobility','resilience'] } })
    ],
    infantry: [
      answer({ id:'infantry_1', label:'Do the job right and you usually live longer.', detailRailTitle:'Do the Job Right', detailRailText:'You trust discipline, fundamentals, and doing the work without drama.', detailTags:['Discipline','Reliability','Precision','Survival'], biases:{ skillBias:['perception','initiative','knowledgeTactics'], prestigeBias:['officer','elite_trooper'], featBias:['rifle_proficiency','point_blank_shot','precise_shot'], talentBias:['accuracy','discipline'] } }),
      answer({ id:'infantry_2', label:'Fancy gets people killed.', detailRailTitle:'Fancy Gets People Killed', detailRailText:'You believe solid fundamentals beat theatrics every time that matters.', detailTags:['Discipline','Simplicity','Reliability','Battlefield Judgment'], biases:{ skillBias:['knowledgeTactics','perception'], prestigeBias:['officer'], featBias:['weapon_focus_rifles','improved_initiative'], talentBias:['discipline','precision'] } }),
      answer({ id:'infantry_3', label:'A rifle, a line, and someone beside you. That\'s enough.', detailRailTitle:'That\'s Enough', detailRailText:'You do not need glory. You need your weapon, your training, and the soldier next to you.', detailTags:['Rifle Work','Cohesion','Discipline','Duty'], biases:{ skillBias:['perception','initiative','treatInjury'], prestigeBias:['officer','vanguard'], featBias:['rifle_proficiency','teamwork'], talentBias:['cohesion','discipline'] } }),
      answer({ id:'infantry_4', label:"Most battles are won by the ones who don't panic.", detailRailTitle:'Don\'t Panic', detailRailText:'You value calm execution over brute aggression.', detailTags:['Composure','Discipline','Initiative','Survival'], biases:{ skillBias:['initiative','knowledgeTactics'], prestigeBias:['officer','elite_trooper'], featBias:['improved_initiative','combat_reflexes'], talentBias:['discipline','control'] } })
    ],
    brawler: [
      answer({ id:'brawler_1', label:"If I'm close enough to hear you breathe, you're in trouble.", detailRailTitle:'Too Close Already', detailRailText:'You believe the fight is already yours once the distance is gone.', detailTags:['Close Combat','Aggression','Confidence','Pressure'], biases:{ skillBias:['jump','climb','initiative'], prestigeBias:['gladiator','martial_artist'], featBias:['martial_arts','rapid_strike','power_attack'], talentBias:['close_combat','assault'] } }),
      answer({ id:'brawler_2', label:"I don't need much room to break somebody.", detailRailTitle:'Don\'t Need Much Room', detailRailText:'Tight spaces, bad angles, and ugly fights do not bother you. They suit you.', detailTags:['Breaching','Close Quarters','Aggression','Practicality'], biases:{ skillBias:['climb','jump','endurance'], prestigeBias:['gladiator','melee_duelist'], featBias:['martial_arts','cleave'], talentBias:['breaching','shock_assault'] } }),
      answer({ id:'brawler_3', label:'Hit hard. Keep hitting.', detailRailTitle:'Keep Hitting', detailRailText:'You trust momentum more than style.', detailTags:['Aggression','Pressure','Endurance','Violence'], biases:{ skillBias:['endurance','initiative'], prestigeBias:['gladiator','vanguard'], featBias:['power_attack','toughness'], talentBias:['assault','pressure'] } }),
      answer({ id:'brawler_4', label:"Up close is where people remember whether they're brave.", detailRailTitle:'Up Close Truth', detailRailText:'You believe close combat strips lies off a person faster than anything else.', detailTags:['Close Combat','Nerve','Presence','Test of Will'], biases:{ skillBias:['initiative','perception'], prestigeBias:['martial_artist','melee_duelist'], featBias:['martial_arts','combat_reflexes'], talentBias:['close_combat','duelist'] } })
    ],
    sergeant: [
      answer({ id:'sergeant_1', label:'Keeping them alive is part of winning.', detailRailTitle:'Winning Means Bringing Them Home', detailRailText:'You believe command means responsibility before glory.', detailTags:['Leadership','Protection','Duty','Recovery'], biases:{ skillBias:['treatInjury','initiative','knowledgeTactics'], prestigeBias:['officer','vanguard'], featBias:['leadership','support'], talentBias:['command','protection'] } }),
      answer({ id:'sergeant_2', label:'A squad without discipline is already dead.', detailRailTitle:'Discipline First', detailRailText:'You think cohesion and discipline decide the fight before the first shot lands.', detailTags:['Discipline','Leadership','Morale','Structure'], biases:{ skillBias:['knowledgeTactics','initiative'], prestigeBias:['officer'], featBias:['leadership','improved_initiative'], talentBias:['command','morale'] } }),
      answer({ id:'sergeant_3', label:'Talk soft if you want. Just make sure they listen.', detailRailTitle:'Make Them Listen', detailRailText:'You know command is not about volume. It is about being obeyed when it counts.', detailTags:['Leadership','Authority','Morale','Control'], biases:{ skillBias:['initiative','knowledgeTactics','treatInjury'], prestigeBias:['officer','elite_trooper'], featBias:['leadership','support'], talentBias:['command','authority'] } }),
      answer({ id:'sergeant_4', label:"I've buried enough soldiers to know what matters.", detailRailTitle:'Know What Matters', detailRailText:'You have seen enough loss to cut straight to what keeps people alive.', detailTags:['Experience','Duty','Judgment','Survival'], biases:{ skillBias:['treatInjury','endurance','knowledgeTactics'], prestigeBias:['officer','vanguard'], featBias:['support','toughness'], talentBias:['judgment','leadership'] } })
    ]
  }
};

const survey = buildSurveyDefinition({
  surveyId: 'L1_Soldier',
  classId: 'soldier',
  displayName: 'Soldier',
  mentorKey: 'Soldier',
  archetypes: [
    { id:'heavy_weapons_specialist', name:'Heavy Weapons Specialist', notes:'You believe firepower solves problems best when it solves many of them at once.', mechanicalBias:{ burstDamage:3, areaDamage:3, areaControl:2 }, roleBias:{ striker:2, controller:2 }, attributeBias:{ strength:2, constitution:2 } },
    { id:'armored_shock_trooper', name:'Tank', notes:'You are built to absorb punishment, hold ground, and keep moving when others would fall.', mechanicalBias:{ damageReduction:3, armorMastery:3, reactionDefense:1 }, roleBias:{ defender:3, bruiser:2 }, attributeBias:{ constitution:3, strength:2 } },
    { id:'precision_rifleman', name:'Infantry', notes:'You trust discipline, marksmanship, and doing the job right without needing flash.', mechanicalBias:{ accuracy:3, critRange:2, singleTargetDamage:2 }, roleBias:{ striker:2, support:1 }, attributeBias:{ dexterity:3, intelligence:1, constitution:1 } },
    { id:'close_quarters_breacher', name:'Brawler', notes:'You settle fights up close, fast, and hard enough that nobody asks for a second round.', mechanicalBias:{ singleTargetDamage:3, meleeDamage:2, evasion:1 }, roleBias:{ bruiser:3, striker:2 }, attributeBias:{ strength:2, dexterity:1, constitution:2 } },
    { id:'battlefield_enforcer', name:'Sergeant', notes:'You measure yourself by the people beside you and whether they come home because you held them together.', mechanicalBias:{ moraleBonus:2, allySupport:2, initiative:1 }, roleBias:{ leader:3, support:2 }, attributeBias:{ charisma:1, wisdom:1, constitution:1 } }
  ],
  questions: [
    {
      id: 'q1_operator_type',
      text: 'What kind of soldier are you?',
      options: [
        answer({ id:'heavy_weapons_specialist', label:'Heavy Weapons Specialist', detailRailTitle:'Heavy Weapons Specialist', detailRailText:'You believe firepower solves problems best when it solves many of them at once.', detailTags:['Autofire','Suppression','Area Pressure','Heavy Weapons'], archetypeHint:'heavy_weapons_specialist', biases:{ skillBias:['initiative','perception','mechanics'], prestigeBias:['elite_trooper','vanguard'], featBias:['heavy_weapons','autofire','suppression'], talentBias:['heavy_weapons','battlefield_pressure'] } }),
        answer({ id:'tank', label:'Tank', detailRailTitle:'Tank', detailRailText:'You are built to absorb punishment, hold ground, and keep moving when others would fall.', detailTags:['Defense','Endurance','Pressure','Lineholding'], archetypeHint:'armored_shock_trooper', biases:{ skillBias:['endurance','initiative','treatInjury'], prestigeBias:['elite_trooper','vanguard','gladiator'], featBias:['defense','toughness','armor'], talentBias:['resilience','defense','shock_assault'] } }),
        answer({ id:'infantry', label:'Infantry', detailRailTitle:'Infantry', detailRailText:'You trust discipline, marksmanship, and doing the job right without needing flash.', detailTags:['Accuracy','Discipline','Reliability','Rifle Work'], archetypeHint:'precision_rifleman', biases:{ skillBias:['perception','initiative','knowledgeTactics'], prestigeBias:['elite_trooper','officer','vanguard'], featBias:['rifle','ranged_accuracy','precision'], talentBias:['accuracy','discipline'] } }),
        answer({ id:'brawler', label:'Brawler', detailRailTitle:'Brawler', detailRailText:'You settle fights up close, fast, and hard enough that nobody asks for a second round.', detailTags:['Close Combat','Aggression','Strength','Pressure'], archetypeHint:'close_quarters_breacher', biases:{ skillBias:['endurance','climb','jump'], prestigeBias:['gladiator','martial_artist','melee_duelist'], featBias:['melee','unarmed','breaching'], talentBias:['close_combat','assault','shock_entry'] } }),
        answer({ id:'sergeant', label:'Sergeant', detailRailTitle:'Sergeant', detailRailText:'You measure yourself by the people beside you and whether they come home because you held them together.', detailTags:['Leadership','Morale','Command','Battlefield Judgment'], archetypeHint:'battlefield_enforcer', biases:{ skillBias:['initiative','knowledgeTactics','treatInjury'], prestigeBias:['officer','elite_trooper','vanguard'], featBias:['leadership','support','battlefield_control'], talentBias:['morale','command','team_support'] } })
      ]
    },
    {
      id: 'q2_first_instinct',
      text: "When the shooting starts, what's your first instinct?",
      options: [
        answer({ id:'return_overwhelming_fire', label:'Return overwhelming fire', detailRailTitle:'Return Overwhelming Fire', detailRailText:'If they started it, you intend to end it louder.', detailTags:['Firepower','Suppression','Initiative','Pressure'], biases:{ skillBias:['initiative','perception'], prestigeBias:['elite_trooper','vanguard'], featBias:['autofire','heavy_weapons','ranged_offense'], talentBias:['suppression','pressure'] } }),
        answer({ id:'hold_the_line', label:'Hold the line', detailRailTitle:'Hold the Line', detailRailText:'Your first thought is to stop the enemy where they stand and make them pay for every step.', detailTags:['Defense','Endurance','Control','Lineholding'], biases:{ skillBias:['endurance','initiative','treatInjury'], prestigeBias:['elite_trooper','vanguard','gladiator'], featBias:['defense','resilience','durability'], talentBias:['defense','battlefield_control'] } }),
        answer({ id:'advance_on_the_enemy', label:'Advance on the enemy', detailRailTitle:'Advance on the Enemy', detailRailText:'You would rather close the distance and make the enemy deal with you directly.', detailTags:['Aggression','Momentum','Mobility','Pressure'], biases:{ skillBias:['jump','climb','initiative'], prestigeBias:['gladiator','martial_artist','melee_duelist'], featBias:['melee','assault','mobility'], talentBias:['breaching','offense','shock_assault'] } }),
        answer({ id:'protect_the_squad', label:'Protect the squad', detailRailTitle:'Protect the Squad', detailRailText:'Your first concern is whether your people stay alive long enough to win.', detailTags:['Protection','Duty','Leadership','Recovery'], biases:{ skillBias:['treatInjury','initiative','endurance'], prestigeBias:['officer','elite_trooper'], featBias:['support','defense','leadership'], talentBias:['command','protection','morale'] } }),
        answer({ id:'strike_the_weak_point', label:'Strike the weak point', detailRailTitle:'Strike the Weak Point', detailRailText:'You are looking for the one place to hit that makes the whole fight tilt your way.', detailTags:['Precision','Tactics','Perception','Initiative'], biases:{ skillBias:['perception','knowledgeTactics','initiative'], prestigeBias:['officer','melee_duelist','vanguard'], featBias:['precision','tactical','offensive'], talentBias:['battlefield_analysis','precision','control'] } })
      ]
    },
    {
      id: 'q3_work_made_you',
      text: 'What kind of work made you a soldier?',
      options: [
        answer({ id:'front_line_service', label:'Front line service', detailRailTitle:'Front Line Service', detailRailText:'You learned what holds and what breaks when people are trying to kill you face-to-face.', detailTags:['Endurance','Initiative','Perception','Battlefield Grit'], biases:{ skillBias:['endurance','initiative','perception'], prestigeBias:['elite_trooper','vanguard'] } }),
        answer({ id:'vehicle_crew_duty', label:'Vehicle crew duty', detailRailTitle:'Vehicle Crew Duty', detailRailText:'You learned war through engines, armor, targeting systems, and keeping a machine alive under fire.', detailTags:['Pilot','Mechanics','Initiative','Systems'], biases:{ skillBias:['pilot','mechanics','initiative'], prestigeBias:['ace_pilot'] } }),
        answer({ id:'siege_work', label:'Siege work', detailRailTitle:'Siege Work', detailRailText:'You learned patience, weight of fire, and how to grind an enemy position down until it stops mattering.', detailTags:['Heavy Weapons','Endurance','Tactics','Pressure'], biases:{ skillBias:['knowledgeTactics','endurance','mechanics'], prestigeBias:['elite_trooper','vanguard'] } }),
        answer({ id:'field_medic_duty', label:'Field medic duty', detailRailTitle:'Field Medic Duty', detailRailText:'You learned that keeping people alive is its own kind of battle, and usually the harder one.', detailTags:['Treat Injury','Endurance','Duty','Recovery'], biases:{ skillBias:['treatInjury','endurance','perception'], prestigeBias:['vanguard','officer'] } }),
        answer({ id:'security_detail', label:'Security detail', detailRailTitle:'Security Detail', detailRailText:'You learned vigilance, discipline, and how to stop trouble before it reached the people you were guarding.', detailTags:['Perception','Initiative','Control','Discipline'], biases:{ skillBias:['perception','initiative','knowledgeTactics'], prestigeBias:['officer','elite_trooper'] } }),
        answer({ id:'boarding_actions', label:'Boarding actions', detailRailTitle:'Boarding Actions', detailRailText:'You learned how to fight in tight spaces, breach hard, and keep moving when there\'s nowhere to fall back to.', detailTags:['Climb','Jump','Initiative','Close Quarters'], biases:{ skillBias:['climb','jump','initiative'], prestigeBias:['gladiator','martial_artist','melee_duelist'] } }),
        answer({ id:'combat_engineering', label:'Combat engineering', detailRailTitle:'Combat Engineering', detailRailText:'You learned that war runs on systems, structure, and knowing exactly what to break first.', detailTags:['Mechanics','Use Computer','Tactics','Systems'], biases:{ skillBias:['mechanics','useComputer','knowledgeTactics'], prestigeBias:['ace_pilot'] } })
      ]
    },
    {
      id: 'q4_future_service',
      text: 'What kind of service are you driving toward?',
      options: [
        answer({ id:'elite_trooper', label:'Leading the charge as an elite trooper', detailRailTitle:'Elite Trooper', detailRailText:'You want to be the one who hits hardest, lasts longest, and keeps advancing when others stop.', detailTags:['Shock Assault','Durability','Firepower','Battlefield Presence'], biases:{ prestigeBias:['elite_trooper'], skillBias:['endurance','initiative'] } }),
        answer({ id:'ace_pilot', label:'Flying where the fight is worst', detailRailTitle:'Ace Pilot', detailRailText:'You want the cockpit, the speed, and the kind of battlefield nobody survives without a pilot who knows what they are doing.', detailTags:['Pilot','Speed','Control','Battlefield Mobility'], biases:{ prestigeBias:['ace_pilot'], skillBias:['pilot','initiative'] } }),
        answer({ id:'officer', label:'Commanding soldiers in battle', detailRailTitle:'Officer', detailRailText:'You want to direct the fight, hold the line together, and make the squad stronger because you were there.', detailTags:['Leadership','Command','Morale','Tactics'], biases:{ prestigeBias:['officer'], skillBias:['knowledgeTactics','initiative','treatInjury'] } }),
        answer({ id:'gladiator', label:'Proving yourself in the arena', detailRailTitle:'Gladiator', detailRailText:'You want strength, endurance, and the kind of reputation only earned through direct combat.', detailTags:['Toughness','Close Combat','Reputation','Endurance'], biases:{ prestigeBias:['gladiator'], skillBias:['endurance','jump'] } }),
        answer({ id:'martial_artist', label:'Mastering the body as a weapon', detailRailTitle:'Martial Artist', detailRailText:'You want discipline, control, and the kind of skill that does not depend on whatever is in your hands.', detailTags:['Unarmed Combat','Discipline','Control','Precision'], biases:{ prestigeBias:['martial_artist'], skillBias:['initiative','jump','climb'] } }),
        answer({ id:'melee_duelist', label:'Becoming the deadliest blade in the fight', detailRailTitle:'Melee Duelist', detailRailText:'You want to win close, clean, and decisively, with skill obvious to anyone who survives seeing it.', detailTags:['Melee','Precision','Timing','Technique'], biases:{ prestigeBias:['melee_duelist'], skillBias:['initiative','perception'] } }),
        answer({ id:'vanguard', label:'Breaking the enemy where they think they\'re strongest', detailRailTitle:'Vanguard', detailRailText:'You want to punch holes in the enemy line and make them watch their best position fail first.', detailTags:['Breach','Pressure','Tactics','Shock'], biases:{ prestigeBias:['vanguard'], skillBias:['knowledgeTactics','initiative','endurance'] } })
      ]
    },
    branchQuestion
  ]
});

export default survey;
