/**
 * Grapple State Machine
 * AUTO-GENERATED BY swse_refactor_build.py
 */


export const GrappleStates = {
  NONE: "none",
  GRABBED: "grabbed",
  GRAPPLED: "grappled",
  PINNED: "pinned"
};

export class GrappleFSM {
  static transition(state, action) {
    const table = {
      none: { attemptGrab: "grabbed" },
      grabbed: { opposedCheck: "grappled" },
      grappled: { pin: "pinned", escape: "none" },
      pinned: { escape: "grappled" }
    };

    return table[state]?.[action] ?? state;
  }
}
