/**
 * SWSE Hotkey Bindings
 * AUTO-GENERATED BY swse_refactor_build.py
 */


Hooks.on("init", () => {
  game.keybindings.register("swse", "openCombatBrowser", {
    name: "Open Combat Action Browser",
    editable: [{ key: "KeyC" }]
  });

  game.keybindings.register("swse", "grapple", {
    name: "Attempt Grapple",
    editable: [{ key: "KeyG" }]
  });
});
