/**
 * Expanded SWSERoll System
 * AUTO-GENERATED BY swse_refactor_build.py
 */


export class SWSERoll {
  constructor(formula, data = {}, options = {}) {
    this.formula = formula;
    this.data = data;
    this.options = options;
  }

  async evaluate() {
    const roll = await new Roll(this.formula, this.data).evaluate();
    return roll;
  }
}

Hooks.on("swse.preReroll", (context) => {
  // middleware hook—user can modify context.roll
});
